version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: >
      redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru

  app_python:
    build: .
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./967_buildings:/app/967_buildings
